CREATE DATABASE TarefasAPI;

CREATE TABLE Tarefas(
IDTarefas UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo NVARCHAR(100) NOT NULL,
Descricao NVARCHAR(255) NOT NULL,
StatusDeConclusao BIT NOT NULL,
DataDeCriacao DATETIME NOT NULL
);